### ISSUE TITLE
Filter triggers NPE

### ISSUE THREAD

**Issue by EinJOJO** [thomasmny/BuildSystem#274]
### Steps to reproduce

1. Open World Manager GUI
2. enter a filter
3. change mode

Inside the world archive it works with no problems

### What is expected?

because of npe the gui does not open.

### What is actually happening?

gui does not open
```

30.06 20:39:59.143] INFO: [Bauserver-1] [20:39:59 ERROR]: Could not pass event InventoryClickEvent to BuildSystem v2.24.5-SNAPSHOT
[30.06 20:39:59.143] INFO: [Bauserver-1] java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.Inventory.getType()" because "inventory" is null
[30.06 20:39:59.143] INFO: [Bauserver-1]        at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftContainer.getNotchInventoryType(CraftContainer.java:108) ~[purpur-1.20.4.jar:git-Purpur-2174]
[30.06 20:39:59.143] INFO: [Bauserver-1]        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:348) ~[purpur-1.20.4.jar:git-Purpur-2174]
[30.06 20:39:59.143] INFO: [Bauserver-1]        at de.eintosti.buildsystem.navigator.inventory.FilteredWorldsInventory.openInventory(FilteredWorldsInventory.java:115) ~[BuildSystem-2.24.5-SNAPSHOT.jar:?]
[30.06 20:39:59.143] INFO: [Bauserver-1]        at de.eintosti.buildsystem.navigator.inventory.NavigatorInventory.onInventoryClick(NavigatorInventory.java:75) ~[BuildSystem-2.24.5-SNAPSHOT.jar:?]
[30.06 20:39:59.143] INFO: [Bauserver-1]        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor136.execute(Unknown Source) ~[?:?]
[30.06 20:39:59.143] INFO: [Bauserver-1]        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2174]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2174]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2174]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3193) ~[?:?]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:25) ~[?:?]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2174]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1498) ~[purpur-1.20.4.jar:git-Purpur-2174]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2174]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1475) ~[purpur-1.20.4.jar:git-Purpur-2174]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1398) ~[purpur-1.20.4.jar:git-Purpur-2174]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1376) ~[purpur-1.20.4.jar:git-Purpur-2174]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[purpur-1.20.4.jar:git-Purpur-2174]
[30.06 20:39:59.144] INFO: [Bauserver-1]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2174]
[30.06 20:39:59.145] INFO: [Bauserver-1]        at java.lang.Thread.run(Thread.java:840) ~[?:?]

```

### Server Info

```shell
Server: git-Purpur-2174 (MC: 1.20.4)*
BuildSystem: 2.24.5-SNAPSHOT
```

**Comment by thomasmny** [comment]
Able to replicate it. 

The issue occurs when a user is on a page that then stops existing when the filter is applied
